"""rbac_discover MCP tool — auto-generate starter policy YAML.

Scans current RBAC state and produces a cloudsight.yaml policy file
with all current assignments as baseline rules plus default governance rules.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

from az_rbac_watch.config.default_rules import DEFAULT_GOVERNANCE_RULES
from az_rbac_watch.config.policy_model import PolicyModel, Rule, RuleMatch, Subscription, save_policy_model
from az_rbac_watch.mcp.azure_scan import scan_subscription_async
from az_rbac_watch.scanner.rbac_scanner import ScannedRoleAssignment

__all__ = ["DISCOVER_TOOL_DEF", "handle_discover"]

logger = logging.getLogger(__name__)

# ── Tool definition ──────────────────────────────────────────────

DISCOVER_TOOL_DEF = {
    "name": "rbac_discover",
    "description": (
        "Generate a starter cloudsight.yaml policy file from your current Azure RBAC "
        "state. Scans all assignments and creates baseline rules for each, plus default "
        "governance rules. Review and customize the generated file before using it with rbac_scan."
    ),
    "inputSchema": {
        "type": "object",
        "properties": {
            "subscriptionId": {
                "type": "string",
                "description": ("Azure subscription ID to scan. Omit to scan all accessible subscriptions."),
            },
            "outputPath": {
                "type": "string",
                "description": "Path to write the generated policy file. Defaults to ./cloudsight.yaml.",
                "default": "./cloudsight.yaml",
            },
        },
    },
}

# ── YAML header comment ─────────────────────────────────────────

_YAML_HEADER = """\
# CloudSight RBAC Policy
# Generated by rbac_discover — review and customize before using.
#
# Baseline rules: assignments that SHOULD exist (drift = anything not listed here)
# Governance rules: patterns that are FORBIDDEN (violations = matches)
"""

# ── Internal helpers ─────────────────────────────────────────────

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(text: str) -> str:
    """Convert text to a lowercase slug for rule names."""
    return _SLUG_RE.sub("-", text.lower()).strip("-")


def _deduplicate_assignments(
    assignments: list[ScannedRoleAssignment],
) -> list[ScannedRoleAssignment]:
    """Deduplicate assignments by (principal_id, role_name, scope)."""
    seen: set[tuple[str, str | None, str]] = set()
    unique: list[ScannedRoleAssignment] = []
    for a in assignments:
        key = (a.principal_id, a.role_name, a.scope)
        if key not in seen:
            seen.add(key)
            unique.append(a)
    return unique


def _build_baseline_rule(assignment: ScannedRoleAssignment) -> Rule:
    """Build a baseline rule from a role assignment."""
    principal_slug = _slugify(assignment.principal_display_name or assignment.principal_id)
    role_slug = _slugify(assignment.role_name or "unknown")
    name = f"baseline-{principal_slug}-{role_slug}"

    description = (
        f"{assignment.principal_display_name or assignment.principal_id} "
        f"— {assignment.role_name or 'unknown'} on {assignment.scope}"
    )

    return Rule(
        name=name,
        type="baseline",
        description=description,
        match=RuleMatch(
            principal_id=assignment.principal_id,
            role=assignment.role_name,
            scope=assignment.scope,
        ),
    )


# ── Public handler ───────────────────────────────────────────────


async def handle_discover(
    subscription_id: str | None = None,
    output_path: str = "./cloudsight.yaml",
) -> str:
    """Scan Azure RBAC and generate a starter cloudsight.yaml policy file.

    Returns JSON with path, summary, and nextSteps.
    """
    from uuid import UUID

    # 1. Scan
    scan_result = await scan_subscription_async(subscription_id)
    all_assignments = scan_result.all_assignments

    # 2. Deduplicate
    unique_assignments = _deduplicate_assignments(all_assignments)

    # 3. Generate baseline rules
    baseline_rules = [_build_baseline_rule(a) for a in unique_assignments]

    # 4. Add default governance rules
    governance_rules = list(DEFAULT_GOVERNANCE_RULES)

    # 5. Build subscriptions list from scan results
    subscriptions = [
        Subscription(id=UUID(sr.subscription_id), name=sr.subscription_name) for sr in scan_result.subscription_results
    ]

    # 6. Build PolicyModel
    all_rules = baseline_rules + governance_rules
    policy = PolicyModel(
        version="2.0",
        tenant_id=UUID("00000000-0000-0000-0000-000000000000"),
        scope="explicit",
        subscriptions=subscriptions,
        rules=all_rules,
    )

    # 7. Write YAML with header comment
    out_path = Path(output_path)
    save_policy_model(policy, out_path)

    # Prepend header comment
    existing = out_path.read_text(encoding="utf-8")
    out_path.write_text(_YAML_HEADER + existing, encoding="utf-8")

    # 8. Build response
    output = {
        "path": output_path,
        "summary": {
            "subscriptionsDiscovered": len(scan_result.subscription_results),
            "assignmentsBaselined": len(unique_assignments),
            "rulesGenerated": len(all_rules),
        },
        "nextSteps": [
            f"Review the generated file at {output_path}",
            "Remove baseline rules for assignments that should NOT exist",
            "Adjust governance rule severities to match your organization's policy",
            "Run rbac_scan with policyPath to see findings against your custom rules",
        ],
    }

    return json.dumps(output, indent=2)
